TEMPLATE_FIELDS = {
    "xu-ly-goc-ra-che-pham": {
        "sectionA": {
            "thangNamBatDauApDung": "Tháng/năm bắt đầu áp dụng xử lý gốc rạ bằng chế phẩm sinh học",
            "soVuXuLyGocRa": "Số vụ xử lý gốc rạ bằng chế phẩm (số vụ/năm x số năm)",
            "thangNamBatDauVuGanDay": "Tháng/năm bắt đầu vụ gần đây",
            "dienTichGocRaSauThuHoach": "Diện tích ruộng có gốc rạ sau thu hoạch được xử lý bằng chế phẩm sinh học (sào/vụ)",
            "chePhamSinhHocSuDung": "Các loại chế phẩm sinh học được sử dụng",
            "tienMuaChePham": "Số tiền chi mua chế phẩm sinh học (đồng/sào)",
            "tienNhanCongPhun": "Số tiền chi nhân công phun chế phẩm sinh học (đồng/sào)",
            "nangSuatLuaSauXuLy": "Năng suất lúa của vụ sau khi xử lý gốc rạ bằng chế phẩm (kg/sào)",
        },
        "sectionB": {
            "16a": "Tên cây trồng được xử lý gốc rạ bằng chế phẩm vi sinh",
            "16btruoc": "Diện tích trồng (sào)",
            "16etruoc": "Cây trồng có bị sâu bệnh không",
            "16ftruoc": "Có sử dụng thuốc trừ sâu không",
            "16gtruoc": "Số tiền mua thuốc trừ sâu (đồng)",
            "16htruoc": "Có sử dụng thuốc diệt cỏ không",
            "16itruoc": "Số tiền mua thuốc diệt cỏ (đồng)",
            "16jtruoc": "Số tiền công lao động (đồng)",
            "16ktruoc": "Số tiền mua hạt giống (đồng)",
            "16ltruoc": "Sản lượng thu hoạch được (kg)",
            "16mtruoc": "Giá bán (đồng/kg)",
            "16ntruoc": "Thành tiền (đồng)",
            "16bsau": "Diện tích trồng (sào)",
            "16esau": "Cây trồng có bị sâu bệnh không",
            "16fsau": "Có sử dụng thuốc trừ sâu không",
            "16gsau": "Số tiền mua thuốc trừ sâu (đồng)",
            "16hsau": "Có sử dụng thuốc diệt cỏ không",
            "16isau": "Số tiền mua thuốc diệt cỏ (đồng)",
            "16jsau": "Số tiền công lao động (đồng)",
            "16ksau": "Số tiền mua hạt giống (đồng)",
            "16lsau": "Sản lượng thu hoạch được (kg)",
            "16msau": "Giá bán (đồng/kg)",
            "16nsau": "Thành tiền (đồng)",
        },
    },
    "len-men-phu-pham": {
        "sectionA": {
            "tenPhuPhamCayTrong": "Tên phụ phẩm cây trồng (sử dụng ủ lên men)",
            "thangNamDau": "Tháng/năm áp dụng kỹ thuật ủ lên men (lần đầu tiên)",
            "dienTichTrong": "Diện tích trồng trong 1 vụ",
            "soLanMen": "Tổng số lần (số vụ) đã tiến hành lên men",
            "thangNamGanNhat": "Tháng/năm bắt đầu vụ gần đây nhất",
            "tenPhuPhamTanDung": "Tên phụ phẩm cây trồng tận dụng để ủ lên men",
            "dienTichDat": "Diện tích đất được sử dụng để trồng cây lấy phụ phẩm ủ lên men (số sào/ vụ)",
            "khoiLuongTrenDong": "Khối lượng phụ phẩm cây trồng có trên đồng ruộng (kg/ sào/ vụ x số sào)",
            "khoiLuongThuGom": "Tổng khối lượng phụ phẩm cây trồng thu gom được (kg/ sào/ vụ x số sào)",
            "khoiLuongSuDungMen": "Tổng khối lượng phụ phẩm cây trồng được sử dụng để ủ lên men (kg/ sào/ vụ x số sào)",
            "khoiLuongThucAnMen": "Khối lượng thức ăn ủ lên men thu được (kg)",
            "mayBamCat": "Sử dụng máy để băm/ cắt nhỏ phụ phẩm cây trồng (có/ không)",
            "nhienLieu": "Lượng nhiên liệu đã sử dụng cho 1 lần lên men (dầu diesel/ hoặc điện; kg/ hoặc giờ)",
            "chiPhiKhac": "Chi phí vật liệu/ đầu vào khác cho 1 lần lên men (ví dụ: thùng, túi ủ, chế phẩm,...)",
        },
        "sectionB": {
            "loaiCayTruoc": "Loại cây trồng",
            "dienTichTruoc": "Diện tích đất trồng cây",
            "loaiPhuPhamTruoc": "Loại phụ phẩm cây trồng",
            "khoiLuongPhuPhamTruoc": "Khối lượng phụ phẩm",
            "khoiLuongThuGomTruoc": "Khối lượng thu gom",
        },
        "sectionC": {
            "tenVatNuoi": "Tên vật nuôi",
            "soLuaSauMen": "Số lứa",
            "soNgayNuoiSauMen": "Số ngày nuôi/lứa",
            "soLuongVatNuoiSau": "Số lượng vật nuôi (con/lứa)",
            "tienThuocSauMen": "Tiền thuốc thú y (đồng/lứa)",
            "vatNuoiBiBenhSau": "Vật nuôi bị bệnh",
            "danhGiaSucKhoeSau": "Đánh giá sức khỏe (1-10)",
            "vatNuoiPhatTrienSau": "Phát triển nhanh hơn",
            "thoiGianNuoiSau": "Thời gian nuôi (tháng)",
            "trongLuongXuatSau": "Trọng lượng xuất chuồng (kg/con)",
            "giaBanSau": "Giá bán (đồng/kg)",
            "thanhTienSau": "Thành tiền (đồng)",
            "soLuaTruocMen": "Số lứa",
            "soNgayNuoiTruocMen": "Số ngày nuôi/lứa",
            "soLuongVatNuoiTruoc": "Số lượng vật nuôi (con/lứa)",
            "tienThuocTruocMen": "Tiền thuốc thú y (đồng/lứa)",
            "vatNuoiBiBenhTruoc": "Vật nuôi bị bệnh",
            "danhGiaSucKhoeTruoc": "Đánh giá sức khỏe (1-10)",
            "vatNuoiPhatTrienTruoc": "Phát triển nhanh hơn",
            "thoiGianNuoiTruoc": "Thời gian nuôi (tháng)",
            "trongLuongXuatTruoc": "Trọng lượng xuất chuồng (kg/con)",
            "giaBanTruoc": "Giá bán (đồng/kg)",
            "thanhTienTruoc": "Thành tiền (đồng)",
        },
    },
    "nuoi-ga-dem-lot": {
        "sectionA": {
            "tenPhuPhamTruoc": "Tên phụ phẩm cây trồng (tận dụng làm đệm lót sinh học dày TỪ TRƯỚC ĐẾN NAY)",
            "thangNamBatDau": "Tháng/năm bắt đầu áp dụng kỹ thuật",
            "tongSoMuaVu": "Tổng số mùa vụ đã tận dụng phụ phẩm để làm đệm lót sinh học dày TỪ TRƯỚC ĐẾN NAY (vụ)",
            "tenCayBonPhan": "Tên những loại cây trồng được bón phân ủ thu được từ lớp đệm lót",
            "dienTichCayBonPhan": "Diện tích cây trồng được bón phân ủ thu được từ lớp đệm lót trong 1 vụ (sào/vụ)",
            "tongSoMuaVuBonPhan": "Tổng số mùa vụ đã được bón phân ủ thu được từ lớp đệm lót",
            "tenPhuPhamDuocTao": "Tên phụ phẩm cây trồng được tận dụng làm đệm lót sinh học dày",
            "dienTichTaoPhuPham": "Diện tích cây trồng tạo ra loại phụ phẩm được tận dụng làm đệm lót sinh học dày (sào)",
            "khoiLuongTrenDong": "Khối lượng phụ phẩm cây trồng có trên đồng ruộng (kg/sào x số sào)",
            "khoiLuongThuGom": "Khối lượng phụ phẩm cây trồng thu gom được (kg/sào x số sào)",
            "tongKhoiLuongLamDemLot": "Tổng khối lượng phụ phẩm cây trồng được tận dụng để làm đệm lót (kg)",
            "tongKhoiLuongPhanU": "Tổng khối lượng phân ủ thu được từ lớp đệm lót (kg)",
            "mayBamCat": "Sử dụng máy để băm/cắt nhỏ phụ phẩm cây trồng",
            "nhienLieu": "Lượng nhiên liệu đã sử dụng (dầu diesel/ hoặc điện)",
            "chiPhiKhac": "Chi phí vật liệu/đầu vào khác (ví dụ: nhân công, chế phẩm, …) (đồng)",
        },
        "sectionB": {
            "loaiCayTruoc": "Loại cây trồng, TRƯỚC KHI áp dụng kỹ thuật",
            "dienTichTruoc": "Diện tích đất trồng cây, TRƯỚC KHI áp dụng kỹ thuật (sào/vụ x số vụ/năm)",
            "loaiPhuPhamTruoc": "Có những loại phụ phẩm cây trồng nào, TRƯỚC KHI áp dụng kỹ thuật",
            "khoiLuongPhuPhamTruoc": "Có bao nhiêu kg phụ phẩm cây trồng tại ruộng/vườn TRƯỚC KHI áp dụng kỹ thuật (kg/sào/vụ x số sào/vụ)",
            "khoiLuongThuGomTruoc": "Có bao nhiêu kg phụ phẩm cây trồng được thu gom TRƯỚC KHI áp dụng kỹ thuật (kg/sào/vụ x số sào/vụ)",
        },
        "phanU": {
            "tenCayTrong": "Tên cây trồng",
            "32bkhong": "Diện tích (sào)",
            "32ekhong": "Số lần phun thuốc trừ sâu hóa học",
            "32fkhong": "Số lượng thuốc sâu hóa học được sử dụng (bình)",
            "32gkhong": "Số lượng thuốc cỏ được sử dụng (bình)",
            "32hkhong": "Số tiền đã chi cho thuốc trừ sâu hóa học (đồng/sào)",
            "32ikhong": "Số tiền đã chi cho thuốc trừ cỏ hóa học (đồng/sào)",
            "32jkhong": "Số tiền công lao động (đồng)",
            "32kkhong": "Số tiền mua hạt giống (đồng/sào)",
            "32lkhong": "Cây trồng có bị sâu bệnh tấn công không?",
            "32mtruoc": "Năng suất thu hoạch (kg/sào)",
            "32ntruoc": "Giá bán (đồng/kg)",
            "32otruoc": "Thành tiền (đồng)",
            "dienTichSauPhanU2": "Diện tích (sào)",
            "32esau": "Số lần phun thuốc trừ sâu hóa học",
            "32fsau": "Số lượng thuốc sâu hóa học được sử dụng (bình)",
            "32gsau": "Số lượng thuốc cỏ được sử dụng (bình)",
            "32hsao": "Số tiền đã chi cho thuốc trừ sâu hóa học (đồng/sào)",
            "32isau": "Số tiền đã chi cho thuốc trừ cỏ hóa học (đồng/sào)",
            "32jsau": "Số tiền công lao động (đồng)",
            "32ksau": "Số tiền mua hạt giống (đồng/sào)",
            "32lsau": "Cây trồng có bị sâu bệnh tấn công không?",
            "32msau": "Năng suất thu hoạch (kg/sào)",
            "32nsau": "Giá bán (đồng/kg)",
            "32osau": "Thành tiền (đồng)",
        },
        "danGa": {
            "soLuongGaSauDemLot": "Số lượng gà trong đợt nuôi (con)",
            "tienThuoc": "Số tiền đã chi cho mua thuốc thú y (đồng)",
            "gioDonDep": "Số giờ dành cho việc dọn dẹp chuồng gà trong 1 tuần",
            "gaBiBenh": "Đàn gà có mắc bệnh gì không",
            "danhGiaSucKhoe": "Đánh giá sức khỏe đàn gà (1-10)",
            "soNgayDatTrongLuong": "Số ngày để đạt được trọng lượng mong muốn",
            "trongLuongXuatChuong": "Trọng lượng trung bình khi xuất chuồng (kg/con)",
            "tongThoiGianNuoi": "Tổng thời gian nuôi đến khi xuất chuồng (tháng)",
            "gaPhatTrienNhanhHon": "Đàn gà có phát triển nhanh hơn và/hoặc lớn hơn",
            "giaBan": "Giá bán (đồng/kg)",
            "tongThuNhap": "Tổng thu nhập",
            "danhGiaMui": "Đánh giá mùi từ chuồng gà (0-10)",
            "soLuongGaTruocDemLot": "Số lượng gà trong đợt nuôi (con)",
            "tienThuoc2": "Số tiền đã chi cho mua thuốc thú y (đồng)",
            "gioDonDep2": "Số giờ dành cho việc dọn dẹp chuồng gà trong 1 tuần",
            "gaBiBenh2": "Đàn gà có mắc bệnh gì không",
            "danhGiaSucKhoe2": "Đánh giá sức khỏe đàn gà (1-10)",
            "soNgayDatTrongLuong2": "Số ngày để đạt được trọng lượng mong muốn",
            "trongLuongXuatChuong2": "Trọng lượng trung bình khi xuất chuồng (kg/con)",
            "tongThoiGianNuoi2": "Tổng thời gian nuôi đến khi xuất chuồng (tháng)",
            "gaPhatTrienNhanhHon2": "Đàn gà có phát triển nhanh hơn và/hoặc lớn hơn",
            "giaBan2": "Giá bán (đồng/kg)",
            "tongThuNhap2": "Tổng thu nhập",
            "danhGiaMui2": "Đánh giá mùi từ chuồng gà (0-10)",
        },
    },
    "nuoi-sau-canxi": {
        "sectionA": {
            "ngayBatDau": "Ngày bắt đầu",
            "soLuaSauCanxi": "Số lứa Sâu canxi đã nuôi",
            "soNgayMotLua": "Số ngày để nuôi một lứa Sâu canxi (TB 45 ngày)",
            "tongChiPhiXayDung": "Tổng chi phí xây dựng khu nuôi Sâu canxi (bao gồm vật liệu và nhân công)",
            "chiPhiMuaGiong": "Chi phí mua giống (trứng Sâu canxi)/tổng số lứa",
            "chiPhiDauVaoKhac": "Chi phí đầu vào/vật liệu khác (cho nuôi sâu canxi)",
            "cachSuDungSauCanxi": "Cách sử dụng Sâu canxi",
            "tenLoaiVatNuoi": "Tên loài vật nuôi được nuôi bằng Sâu canxi",
            "soLuongConVatNuoi": "Số lượng con vật nuôi/lứa",
            "soLuaVatNuoi": "Số lứa (được cho ăn Sâu canxi)",
            "cachSuDungPhanSauCanxi": "Cách sử dụng phân Sâu canxi",
            "tenCayTrongPhanSauCanxi": "Tên những loài cây trồng được bón bằng phân Sâu canxi (1 ô ghi 1 loại cây trồng)",
            "tongSoVuTrongPhanSauCanxi": "Tổng số vụ trồng (sử dụng phân bón Sâu canxi; số vụ/năm)",
            "dienTichCayTrongPhanSauCanxi": "Diện tích cây trồng được bón phân Sâu canxi (số sào/vụ)",
        },
        "sectionB": {
            "loaiPhuPhamThucAn": "Loại phụ phẩm nông nghiệp làm thức ăn cho Sâu canxi",
            "khoiLuongPhuPhamTB": "Khối lượng phụ phẩm nông nghiệp thải trung bình mỗi ngày",
            "soLuongVatNuoi": "Số lượng từng loại vật nuôi",
            "soNgayLuaNuoi": "Số ngày/lứa nuôi",
            "soLuaNuoi": "Số lứa nuôi",
            "tongKhoiLuongPhuPhamSX": "Tổng khối lượng phụ phẩm nông nghiệp sản xuất ra được (kg/ngày)",
            "khoiLuongPhuPhamDungChoSauCanxi": "Khối lượng phụ phẩm nông nghiệp dùng cho sâu canxi (kg/ngày)",
            "tyLePhuPhamDungChoSauCanxi": "Tỷ lệ % phụ phẩm nông nghiệp dùng cho sâu canxi",
            "dienTichNuoiSauCanxi": "Diện tích được sử dụng để nuôi sâu canxi (m2/lứa)",
            "chiPhiMuaGiongB": "Chi phí mua giống (trứng sâu canxi, tính cho 1m2/lứa)",
            "soNgayDeNuoiMotLuaB": "Số ngày để nuôi một lứa sâu canxi (ngày)",
            "khoiLuongSauCanxiThuDuoc": "Khối lượng sâu canxi thu được (kg/lứa)",
            "khoiLuongPhanSauCanxiThuDuoc": "Khối lượng phân sâu canxi thu được (kg/lứa)",
            "congLaoDong": "Công lao động (số giờ/ngày)",
        },
        "sectionC": {
            "tenCayTrong": "Tên loại cây trồng được bón phân sâu canxi",
            "26bkhong": "26b. Cây được trồng tháng/năm nào? (KHÔNG BÓN)",
            "26ckhong": "26c. Diện tích trồng (sào/vụ) (KHÔNG BÓN)",
            "26bsau": "26b. Cây được trồng tháng/năm nào? (SAU KHI BÓN)",
            "26csau": "26c. Diện tích trồng (sào/vụ) (SAU KHI BÓN)",
            "32ekhong": "26f. Số lần phun thuốc trừ sâu hóa học (KHÔNG BÓN)",
            "32fkhong": "26g. Số lượng thuốc trừ sâu hóa học (bình 15-20l/sào/vụ) (KHÔNG BÓN)",
            "32gkhong": "26h. Số lượng thuốc trừ cỏ (bình 15-20l/sào/vụ) (KHÔNG BÓN)",
            "32hkhong": "26i. Số tiền thuốc trừ sâu hóa học (đồng/sào/vụ) (KHÔNG BÓN)",
            "32ikhong": "26j. Số tiền thuốc trừ cỏ hóa học (đồng/sào/vụ) (KHÔNG BÓN)",
            "32jkhong": "26k. Số tiền công chăm sóc cây trồng (đồng/sào/vụ) (KHÔNG BÓN)",
            "32kkhong": "26l. Số tiền mua hạt giống (đồng/sào/vụ) (KHÔNG BÓN)",
            "32lkhong": "26m. Cây trồng có bị sâu bệnh tấn công (KHÔNG BÓN)",
            "32mtruoc": "26n. Năng suất thu hoạch (kg/sào) (KHÔNG BÓN)",
            "32ntruoc": "26o. Giá bán (đồng/kg) (KHÔNG BÓN)",
            "32otruoc": "26p. Thành tiền (đồng) (KHÔNG BÓN)",
            "32esau": "26f. Số lần phun thuốc trừ sâu hóa học (SAU KHI BÓN)",
            "32fsau": "26g. Số lượng thuốc trừ sâu hóa học (bình 15-20l/sào/vụ) (SAU KHI BÓN)",
            "32gsau": "26h. Số lượng thuốc trừ cỏ (bình 15-20l/sào/vụ) (SAU KHI BÓN)",
            "32hsao": "26i. Số tiền thuốc trừ sâu hóa học (đồng/sào/vụ) (SAU KHI BÓN)",
            "32isau": "26j. Số tiền thuốc trừ cỏ hóa học (đồng/sào/vụ) (SAU KHI BÓN)",
            "32jsau": "26k. Số tiền công chăm sóc cây trồng (đồng/sào/vụ) (SAU KHI BÓN)",
            "32ksau": "26l. Số tiền mua hạt giống (đồng/sào/vụ) (SAU KHI BÓN)",
            "32lsau": "26m. Cây trồng có bị sâu bệnh tấn công (SAU KHI BÓN)",
            "32msau": "26n. Năng suất thu hoạch (kg/sào) (SAU KHI BÓN)",
            "32nsau": "26o. Giá bán (đồng/kg) (SAU KHI BÓN)",
            "32osau": "26p. Thành tiền (đồng) (SAU KHI BÓN)",
        },
        "sectionD": {
            "loaiVatNuoi": "Loại vật nuôi",
            "29akhong": "29a. Số con vật nuôi (con/lứa) (KHÔNG SỬ DỤNG SÂU CANXI)",
            "29asau": "29a. Số con vật nuôi (con/lứa) (SAU KHI SỬ DỤNG SÂU CANXI)",
            "29dkhong": "29d. Số tiền thuốc thú y/lứa (đồng) (KHÔNG SỬ DỤNG)",
            "29ekhong": "29e. Vật nuôi có bị bất kỳ bệnh nào không (KHÔNG SỬ DỤNG)",
            "29fkhong": "29f. Đánh giá sức khỏe vật nuôi (1-10) (KHÔNG SỬ DỤNG)",
            "29gkhong": "29g. Vật nuôi phát triển nhanh hơn/lớn hơn (KHÔNG SỬ DỤNG)",
            "29hkhong": "29h. Thời gian nuôi đến xuất chuồng (tháng) (KHÔNG SỬ DỤNG)",
            "29ikhong": "29i. Trọng lượng TB khi xuất chuồng (kg/con) (KHÔNG SỬ DỤNG)",
            "29jkhong": "29j. Giá bán (đồng/kg) (KHÔNG SỬ DỤNG)",
            "29kkhong": "29k. Thành tiền (đồng) (KHÔNG SỬ DỤNG)",
            "29dsau": "29d. Số tiền thuốc thú y/lứa (đồng) (SAU KHI SỬ DỤNG)",
            "29esau": "29e. Vật nuôi có bị bất kỳ bệnh nào không (SAU KHI SỬ DỤNG)",
            "29fsau": "29f. Đánh giá sức khỏe vật nuôi (1-10) (SAU KHI SỬ DỤNG)",
            "29gsau": "29g. Vật nuôi phát triển nhanh hơn/lớn hơn (SAU KHI SỬ DỤNG)",
            "29hsau": "29h. Thời gian nuôi đến xuất chuồng (tháng) (SAU KHI SỬ DỤNG)",
            "29isau": "29i. Trọng lượng TB khi xuất chuồng (kg/con) (SAU KHI SỬ DỤNG)",
            "29jsau": "29j. Giá bán (đồng/kg) (SAU KHI SỬ DỤNG)",
            "29ksau": "29k. Thành tiền (đồng) (SAU KHI SỬ DỤNG)",
        },
    },
    "nuoi-trun-que": {
        "sectionA": {
            "ngayBatDau": "Ngày bắt đầu",
            "soLuaTrunQue": "Số lứa trùn quế đã nuôi",
            "soNgayMotLua": "Số ngày để nuôi một lứa trùn quế (bắt đầu thả sinh khối – thu hoạch, TB 60 ngày)",
            "tongChiPhiXayDung": "Tổng chi phí xây dựng khu nuôi trùn quế (bao gồm vật liệu và nhân công)",
            "chiPhiMuaGiong": "Chi phí mua giống (sinh khối trùn quế)",
            "chiPhiDauVaoKhac": "Chi phí đầu vào/vật liệu khác (cho Trùn quế)",
            "cachSuDungTrunQue": "Cách sử dụng trùn quế",
            "tenLoaiVatNuoi": "Tên loài vật nuôi được nuôi bằng trùn quế",
            "soLuongConVatNuoi": "Số lượng con vật nuôi/lứa",
            "soLuaVatNuoi": "Số lứa (được cho ăn trùn quế)",
            "cachSuDungPhanTrunQue": "Cách sử dụng phân trùn quế",
            "tenCayTrongPhanTrunQue": "Nêu tên những loài cây trồng được bón bằng phân trùn quế (1 ô ghi 1 loại cây trồng)",
            "tongSoVuTrongPhanTrunQue": "Tổng số vụ trồng (sử dụng phân bón trùn quế/vụ; số vụ/năm x số năm)",
            "dienTichCayTrongPhanTrunQue": "Diện tích cây trồng được bón phân trùn quế (số sào/vụ x số vụ/năm)",
        },
        "sectionB": {
            "loaiPhuPhamThucAn": "Loại phụ phẩm nông nghiệp làm thức ăn cho trùn quế",
            "khoiLuongPhuPhamTB": "Khối lượng phụ phẩm nông nghiệp thải trung bình mỗi ngày (kg/con/ngày)",
            "soLuongVatNuoi": "Số lượng từng loại vật nuôi",
            "soNgayLuaNuoi": "Số ngày/lứa nuôi",
            "soLuaNuoi": "Số lứa nuôi",
            "tongKhoiLuongPhuPhamSX": "Tổng khối lượng phụ phẩm nông nghiệp sản xuất ra được (kg)",
            "khoiLuongPhuPhamDungChoTrunQue": "Khối lượng phụ phẩm nông nghiệp dùng cho trùn quế (kg/ngày)",
            "tyLePhuPhamDungChoTrunQue": "Tỷ lệ % phụ phẩm nông nghiệp dùng cho trùn quế (19g/19f)",
            "dienTichNuoiTrunQue": "Diện tích được sử dụng để nuôi trùn quế (m2/lứa)",
            "chiPhiMuaGiongB": "Chi phí mua giống (sinh khối trùn quế, tính cho 1m2/lứa)",
            "soNgayDeNuoiMotLuaB": "Số ngày để nuôi một lứa trùn quế (ngày)",
            "khoiLuongTrunQueThuDuoc": "Khối lượng trùn quế thu được (kg/lứa)",
            "khoiLuongPhanTrunQueThuDuoc": "Khối lượng phân trùn quế thu được (kg/lứa)",
            "congLaoDong": "Công lao động (số giờ/ngày)",
            "gioQuetDonPhanChuongTruoc": "Khi chưa nuôi trùn quế, trong 1 ngày dành bao nhiêu giờ để quét dọn phân chuồng",
            "gioDonPhanChuongSau": "Khi nuôi trùn quế, 1 ngày dành bao nhiêu giờ để dọn dẹp phân chuồng dùng cho trùn quế",
        },
        "sectionC": {
            "20a": "Nêu tên loại cây trồng được bón phân trùn quế",
            "20btruoc": "20b. Cây được trồng tháng/năm nào? (KHÔNG BÓN)",
            "20ctruoc": "20c. Diện tích trồng (sào/vụ) (KHÔNG BÓN)",
            "20bsau": "20b. Cây được trồng tháng/năm nào? (SAU KHI BÓN)",
            "20csau": "20c. Diện tích trồng (sào/vụ) (SAU KHI BÓN)",
            "20ftruoc": "20f. Số lần phun thuốc trừ sâu hóa học (KHÔNG BÓN)",
            "20gtruoc": "20g. Số lượng thuốc trừ sâu hóa học (bình 15-20l/sào/vụ) (KHÔNG BÓN)",
            "20htruoc": "20h. Số lượng thuốc trừ cỏ (bình 15-20l/sào/vụ) (KHÔNG BÓN)",
            "20itruoc": "20i. Số tiền thuốc trừ sâu hóa học (đồng/sào/vụ) (KHÔNG BÓN)",
            "20jtruoc": "20j. Số tiền thuốc trừ cỏ hóa học (đồng/sào/vụ) (KHÔNG BÓN)",
            "20ktruoc": "20k. Số tiền công chăm sóc cây trồng (đồng/sào/vụ) (KHÔNG BÓN)",
            "20ltruoc": "20l. Số tiền mua hạt giống (đồng/sào/vụ) (KHÔNG BÓN)",
            "20mtruoc": "20m. Cây trồng có bị sâu bệnh tấn công (KHÔNG BÓN)",
            "20ntruoc": "20n. Năng suất thu hoạch (kg/sào) (KHÔNG BÓN)",
            "20otruoc": "20o. Giá bán (đồng/kg) (KHÔNG BÓN)",
            "20ptruoc": "20p. Thành tiền (đồng) (KHÔNG BÓN)",
            "20fsau": "20f. Số lần phun thuốc trừ sâu hóa học (SAU KHI BÓN)",
            "20gsau": "20g. Số lượng thuốc trừ sâu hóa học (bình 15-20l/sào/vụ) (SAU KHI BÓN)",
            "20hsau": "20h. Số lượng thuốc trừ cỏ (bình 15-20l/sào/vụ) (SAU KHI BÓN)",
            "20isau": "20i. Số tiền thuốc trừ sâu hóa học (đồng/sào/vụ) (SAU KHI BÓN)",
            "20jsau": "20j. Số tiền thuốc trừ cỏ hóa học (đồng/sào/vụ) (SAU KHI BÓN)",
            "20ksau": "20k. Số tiền công chăm sóc cây trồng (đồng/sào/vụ) (SAU KHI BÓN)",
            "20lsau": "20l. Số tiền mua hạt giống (đồng/sào/vụ) (SAU KHI BÓN)",
            "20msau": "20m. Cây trồng có bị sâu bệnh tấn công (SAU KHI BÓN)",
            "20nsau": "20n. Năng suất thu hoạch (kg/sào) (SAU KHI BÓN)",
            "20osau": "20o. Giá bán (đồng/kg) (SAU KHI BÓN)",
            "20psau": "20p. Thành tiền (đồng) (SAU KHI BÓN)",
        },
        "sectionD": {
            "21a": "Loại vật nuôi",
            "29akhong": "21b. Số con vật nuôi (con/lứa) (KHÔNG SỬ DỤNG TRÙN QUẾ)",
            "29asau": "21b. Số con vật nuôi (con/lứa) (SAU KHI SỬ DỤNG TRÙN QUẾ)",
            "29dkhong": "21e. Số tiền thuốc thú y (đồng) (KHÔNG SỬ DỤNG)",
            "29ekhong": "21f. Vật nuôi có bị bất kỳ bệnh nào không (KHÔNG SỬ DỤNG)",
            "29fkhong": "21g. Đánh giá sức khỏe vật nuôi (1-10) (KHÔNG SỬ DỤNG)",
            "29gkhong": "21h. Vật nuôi phát triển nhanh hơn/lớn hơn (KHÔNG SỬ DỤNG)",
            "29hkhong": "21i. Thời gian nuôi đến xuất chuồng (tháng) (KHÔNG SỬ DỤNG)",
            "29ikhong": "21j. Trọng lượng TB khi xuất chuồng (kg/con) (KHÔNG SỬ DỤNG)",
            "29jkhong": "21k. Giá bán (đồng/kg) (KHÔNG SỬ DỤNG)",
            "29kkhong": "21l. Thành tiền (đồng) (KHÔNG SỬ DỤNG)",
            "29dsau": "21e. Số tiền thuốc thú y (đồng) (SAU KHI SỬ DỤNG)",
            "29esau": "21f. Vật nuôi có bị bất kỳ bệnh nào không (SAU KHI SỬ DỤNG)",
            "29fsau": "21g. Đánh giá sức khỏe vật nuôi (1-10) (SAU KHI SỬ DỤNG)",
            "29gsau": "21h. Vật nuôi phát triển nhanh hơn/lớn hơn (SAU KHI SỬ DỤNG)",
            "29hsau": "21i. Thời gian nuôi đến xuất chuồng (tháng) (SAU KHI SỬ DỤNG)",
            "29isau": "21j. Trọng lượng TB khi xuất chuồng (kg/con) (SAU KHI SỬ DỤNG)",
            "29jsau": "21k. Giá bán (đồng/kg) (SAU KHI SỬ DỤNG)",
            "29ksau": "21l. Thành tiền (đồng) (SAU KHI SỬ DỤNG)",
        },
    },
    "u-phan-huu-co-tai-ruong": {
        "sectionA": {
            "tenPhuPham": "Tên phụ phẩm cây trồng (tận dụng ủ phân từ trước đến nay)",
            "thangNamBatDau": "Tháng/năm bắt đầu tiến hành ủ phân",
            "tenPhuPhamTanDung": "Tên phụ phẩm cây trồng tận dụng để ủ phân",
            "khoiLuongPhuPhamTrenRuong": "Khối lượng phụ phẩm cây trồng có trên đồng ruộng (kg/sào x số sào)",
            "khoiLuongPhuPhamThuGom": "Khối lượng phụ phẩm cây trồng thu gom được (kg/sào x số sào)",
            "tongKhoiLuongPhuPhamSuDung": "Tổng khối lượng phụ phẩm cây trồng được sử dụng để ủ phân (kg/sào x số sào)",
            "khoiLuongPhanHuuCoThuDuoc": "Khối lượng phân hữu cơ thu được sau khi ủ (kg/sào x số sào)",
            "nhungLoaiCayDuocBonPhan": "Những loại cây trồng được bón phân ủ hữu cơ (1 ô ghi 1 loại cây trồng)",
            "tongSoMuaVuBonPhan": "Tổng số mùa vụ đã được bón phân ủ hữu cơ (theo từng loại cây trồng)",
            "dienTichCayDuocBonPhan": "Diện tích cây trồng được bón phân ủ hữu cơ (số sào/vụ)",
            "suDungMayCatNho": "Sử dụng máy để băm/cắt nhỏ phụ phẩm cây trồng",
            "nhienLieuSuDung": "Lượng nhiên liệu đã sử dụng (dầu diesel/ hoặc điện)",
            "chiPhiVatLieuKhac": "Chi phí vật liệu/đầu vào khác (nhân công, ống thông khí, bạt, chế phẩm, rỉ mật…) (đồng)",
        },
        "sectionB": {
            "loaiCayTrongTruoc": "Loại cây trồng",
            "coTrongTruoc": "Có trồng không?",
            "dienTichDatTruoc": "Diện tích đất trồng cây (sào/vụ x số vụ/năm)",
            "tenPhuPhamTruoc": "Tên phụ phẩm cây trồng (ghi tên từng loại)",
            "khoiLuongPhuPhamTruoc": "Khối lượng phụ phẩm cây trồng (kg/sào/vụ x số sào)",
            "khoiLuongPhuPhamThuGomTruoc": "Khối lượng phụ phẩm cây trồng được thu gom (kg/sào/vụ x số sào)",
        },
        "sectionC": {
            "20a": "Tên cây trồng được bón phân ủ hữu cơ",
            "20ctruoc": "11b. Diện tích (sào/vụ) (KHÔNG BÓN)",
            "20csau": "11b. Diện tích (sào/vụ) (SAU KHI BÓN)",
            "20ftruoc": "11e. Cây trồng có bị sâu bệnh không (KHÔNG BÓN)",
            "20gtruoc": "11f. Có sử dụng thuốc trừ sâu không (KHÔNG BÓN)",
            "20htruoc": "11g. Số tiền mua thuốc trừ sâu (đồng/sào) (KHÔNG BÓN)",
            "20itruoc": "11h. Số tiền mua thuốc diệt cỏ (đồng/sào) (KHÔNG BÓN)",
            "20jtruoc": "11i. Số tiền công lao động (đồng) (KHÔNG BÓN)",
            "20ktruoc": "11j. Số tiền mua hạt giống (đồng/sào) (KHÔNG BÓN)",
            "20ltruoc": "11k. Năng suất thu hoạch được (kg/sào) (KHÔNG BÓN)",
            "20mtruoc": "11l. Giá bán (đồng/kg) (KHÔNG BÓN)",
            "20ntruoc": "11m. Thành tiền (đồng) (KHÔNG BÓN)",
            "20fsau": "11e. Cây trồng có bị sâu bệnh không (SAU KHI BÓN)",
            "20gsau": "11f. Có sử dụng thuốc trừ sâu không (SAU KHI BÓN)",
            "20hsau": "11g. Số tiền mua thuốc trừ sâu (đồng/sào) (SAU KHI BÓN)",
            "20isau": "11h. Số tiền mua thuốc diệt cỏ (đồng/sào) (SAU KHI BÓN)",
            "20jsau": "11i. Số tiền công lao động (đồng) (SAU KHI BÓN)",
            "20ksau": "11j. Số tiền mua hạt giống (đồng/sào) (SAU KHI BÓN)",
            "20lsau": "11k. Năng suất thu hoạch được (kg/sào) (SAU KHI BÓN)",
            "20msau": "11l. Giá bán (đồng/kg) (SAU KHI BÓN)",
            "20nsau": "11m. Thành tiền (đồng) (SAU KHI BÓN)",
        },
    },
}
